<?php
// language specific strings for use in Oval Office

// syntax: define('VAR', 'value');
/*
define('','');
define('','');
define('','');
define('','');
define('','');
define('','');
*/

define('GAME_ICON_SERVER','http://data.dieverdammten.de/gfx/icons/item_');
define('GAMESERVER_ITEM','http://data.dieverdammten.de/gfx/icons/item_');
define('GAMESERVER_TAG','http://data.dieverdammten.de/gfx/icons/tag_');
define('GAMESERVER_ICON','http://data.dieverdammten.de/gfx/icons/');
define('GAMESERVER_SMILEY','http://www.dieverdammten.de/gfx/forum/smiley/');

define('DATETIME_FULL', '%e. %B %Y | %H:%M');
define('DATETIME_MINI', '%e.%m.%Y, %H:%M');

# global
define('VERSION','Version');
define('MAINTENANCE_MSG','Ein paar wildgewordene Ghule haben die Tapeten ruiniert. Bitte gedulden Sie sich einen Moment, bis wir das wieder in Ordnung gebracht haben.');
define('ERROR', 'Fehler! Ganz einfach ein Fehler. Schreib im Wartebereich doch mal hin, wo Du das hier liest, dann kann Sin evtl. was damit anfangen.');
define('ERROR_CODE', 'Fehlercode');
define('ERROR_XML_DEFAULT', 'Fehler in der XML-Verarbeitung.');
define('CATEGORY','Kategorie');
define('ITEM','Gegenstand');
define('ON','an');
define('DAY','Tag');
define('DAYS','Tage');
define('DAYS_DATIV','Tagen');
define('STATUS_QUO','Stand');
define('TIME_APPENDIX',' Uhr');
define('CAUTION', 'Achtung');
define('AMP','&');
define('NOTE','Hinweis');
define('PRESET_SAVE', 'Als Vorlage speichern');
define('PRESET_LOAD', 'Vorlage laden');
define('PRESET_SAVED', 'Vorlage gespeichert.');
define('PRESET_LOADED', 'Vorlage geladen.');
define('ERROR_OCCURED', 'Ein Fehler ist aufgetreten.');
define('COUNT', 'Anzahl');
define('AMOUNT', 'Anzahl');
define('ENTER_VALUES', 'Eintragen');
define('NAME', 'Name');
define('LOCATION', 'Aufenthaltsort');
define('DEATHCAUSE', 'Todesursache');
define('SEASON','Saison');
define('STATS_DEFOE','S%d Normal');
define('STATS_HARD','S%d Panda');
// jobs
define('RESIDENT', 'Einwohner');
define('CITIZEN', 'Bürger');
define('CITIZEN_NOJOB', 'Arbeitssuchend');
define('HERO','Held');
define('HEROS','Helden');
define('SCAVENGER', 'Buddler');
define('SCOUT', 'Aufklärer');
define('TAMER', 'Dompteur');
define('GUARDIAN', 'Wächter');
define('HUNTER', 'Einsiedler');
define('TECH', 'Techniker');
define('SHAMAN', 'Schamane');
define('DEAD_CITIZEN', 'Verstorben');
define('DEADS','Tote');
define('BANNED','Verbannte');
define('AP', 'AP');
define('CP', 'KP');
define('KM', 'km');
// city and directions
define('CITY', 'Stadt');
define('Nx','Norden');
define('Wx','Westen');
define('Sx','Süden');
define('Ex','Osten');
define('NEx','Nordosten');
define('NWx','Nordwesten');
define('SEx','Südosten');
define('SWx','Südwesten');
define('N','N');
define('W','W');
define('S','S');
define('E','O');
define('NE','NO');
define('NW','NW');
define('SE','SO');
define('SW','SW');
define('ZOMBIE', 'Zombie');
define('ZOMBIES', 'Zombies');
define('ZOMBIEX','%s');
define('EXISTENT','vorhanden');
define('TODAY','heute');
define('YESTERDAY','gestern');
define('APPROXY','ca.');
define('DEFOE_TOWN','Normale Städte');
define('HARD_TOWN','Pandämonium-Städte');

define('FOYER_INTRO','Willkommen');
define('FOYER_ID','Identifikation');
define('FOYER_GM','Addons & Erweiterungen');

# mail
define('YOUR_MAILBOX', 'Oval Office Postamt');
define('YOUR_MESSAGES', 'Deine Nachrichten');
define('YOUR_FRIENDS', 'Deine Kontakte');
define('INVITE', 'Einladen');
define('USER_NOT_YET_LOGGED_IN', 'Dieser Nutzer hat sein Postfach bisher noch nicht aktiviert.');
define('USER_UNKNOWN', 'Kein Nutzer mit diesem Namen bekannt.');
define('USER_IGNORES_YOU', 'Dieser Nutzer möchte keinen Kontakt mit Dir.');
define('USER_INVITED_YOU', 'Dieser Nutzer hat Dich bereits eingeladen. Beantworte bitte diese Einladung.');
define('USER_ALREADY_INVITED', 'Diesen Nutzer hast Du bereits eingeladen. Warte bitte auf die Antwort.');
define('USER_INVITED','Du hast %s in Deine Freundesliste eingeladen.');
define('USER_NOT_YOUR_FRIEND','Dieser Nutzer ist noch nicht in Deiner Kontaktliste.');
define('PENDING','Ausstehend');
define('INVITES', 'Einladungen');
define('ACTIVE_CONTACTS','Freunde');
define('ACCEPT_REQUEST','Einladung annehmen');
define('DECLINE_REQUEST','Einladung ablehnen');
define('IGNORE_REQUEST','Spieler ignorieren');
define('SEND_MSG', 'Nachricht senden');
define('MSG_SENT', 'Nachricht gesendet.');
define('USER_ACCEPTED', '%s ist nun in Deiner Freundesliste.');
define('FROM','Von');
define('TO','An');
define('SUBJECT','Betreff');
define('TIME_SENT','Gesendet');
define('TIME_RECEIVED','Empfangen');
define('TRASH','Entf');
define('TRASH_MAIL','Nachricht löschen');
define('NO_MSGS','Keine Nachrichten');
define('ANSWER_MSG','Auf Nachricht antworten');
define('SELFINVITE','Traurig, dass Du Dich selbst einladen musst. Hast Du keine Freunde?');
define('USER_DECLINED', 'Du hast die Einladung von %s abgelehnt.');
define('USER_DELETED', '%s ist nun nicht mehr in Deiner Kontaktliste.');
define('DELETE_CONTACT', 'Kontakt entfernen');
define('USER_WITHDRAWN', 'Du hast die Einladung an %s zurückgezogen.');
define('WITHDRAW_INVITE', 'Einladung zurückziehen');

# bank
define('Rsc', 'Baumaterialien');
define('Food', 'Lebensmittel');
define('Armor', 'Verteidigung');
define('Drug', 'Apothekenpflichtiges');
define('Weapon', 'Waffenarsenal');
define('Misc', 'Sonstiges');
define('Furniture', 'Deko & Ausbau');
define('Box', 'Taschen & Wagen');
define('PROVIANT','Vorräte');
define('GRAPH_SETTINGS', 'Einstellungen für Grafiken');
define('GRAPH_TYPE', 'Diagrammtyp');
define('GRAPH_BARS', 'Balken');
define('GRAPH_LINES', 'Linien');
define('GRAPH_MAX_VALUES','Maximal-Anzahl Kohorten');
define('BANK_CONTENT', 'Bankinhalt');
define('BANK_CHANGE_MSG', 'Zahlen in Klammern spiegeln die Veränderung gegenüber dem Vortag wider.<br/>(Letzter Aktualisierungszeitpunkt gestern war %s.)');
define('BROKEN', 'kaputt');
define('BANK_HISTORY_MSG', 'In einem alten verstaubten Buch auf einer Art Altar entdeckst Du Zeichnungen von Objekten, die Du nur noch vage in Erinnerung hast.');
define('BANK_WATSON_MSG', '<h4>Forensische Bank-Investigation</h4>Irgendetwas stimmt nicht in der Bank? Registereinträge wurden verfälscht? Und Du willst wissen, was fehlt? Kopiere das Bank-Log von heute hier rein (und ggf. die Einträge, die gestern nach %s Uhr gemacht wurden) und klicke auf <em>FBI starten</em>!');
define('GRAPH_BANK_TITLE','Entwicklung der Inventarzahlen');
define('WWATER','Wasser (Bank)');
define('WWELL','Wasser (Brunnen)');
define('FOOD','Nahrungsmittel');
define('DRUGS','Drogen');
define('ALCOHOL','Alkohol');
define('COFFEE','Kaffee');

# bauamt
define('CONSTRUCTION_YARD_TITLE','Das Bauamt');
define('SELECT_NONE','Auswahl löschen');
define('SELECT_ALL','Alles auswählen');
define('SHOW_ALL','Alle anzeigen');
define('SHOW_BPONLY','Nur verfügbare anzeigen');
define('GET_CONSTRUCTION_PERMIT','Bauantrag stellen');
define('ALREADY_BUILT','Bereits gebaut!');
define('MARK_AS_ALREADY_BUILT','Als `Bereits gebaut!´ markieren');
define('MARK_AS_DESTROYED','Gebäude abreißen');
define('MARK_AS_BLUEPRINT_FOUND','Blaupause vorhanden?');
define('MARK_AS_BLUEPRINT_LOSE','Blaupause verloren?');
define('TEMPORARY_BUILDING','Temporäres Gebäude');
define('REMAINS','verbleibt');
define('REMAIN','verbleiben');
define('ITEMS_REMAINING', 'Es %s %d.');
define('MISSES','fehlt');
define('MISS','fehlen');
define('ITEMS_MISSING', 'Es %s noch %d!');
define('CONSTRUCTION_PERMIT_REQUESTED', 'Bauantrag gestellt für %d Gebäude');
define('VP_GAIN', 'Der Bau wird insgesamt %s VP bringen.');
define('WILLS','wird');
define('WILL','werden');
define('VP_ITEM','Verteidigungsgegenstand');
define('VP_ITEMS','Verteidigungsgegenstände');
define('VP_USE','Allerdings %s %d %t verbraucht.');
define('REQUIRED_RESOURCES','Benötigte Baustoffe');
define('REQUIRED_AP_BUILD','Benötigte AP für den Bau');
define('REQUIRED_AP_WORKSHOP','Benötigte AP in der Werkstatt');
define('CONSTRUCTION_PERMIT','BAUGENEHMIGUNG');
define('REQUESTED_BY','ausgefertigt im Oval Office auf Antrag von %s');
define('CONSTRUCTIONS_PERMITTED','Genehmigt %s [g]%d Gebäude[/g]');
define('HAS_BEEN','wurde');
define('HAVE_BEEN','wurden');
define('WORKSHOP_CONVERSIONS', 'In der Werkstatt könnten erzeugt werden');
define('REQUIRED_STEPS', '%d Schritte notwendig.');
define('FACTORY','Manufaktur');
define('SAW','Säge');
define('EXIST','vorhanden');
define('PERMIT_COPY_NOTICE', 'Mit <span style="font-variant:small-caps;">Strg/Ctrl+C</span> kannst Du die Baugenehmigung in die Zwischenablage kopieren und von dort aus per <span style="font-variant:small-caps;">Strg/Ctrl+V</span> im Stadtforum einfügen.');

# ema
define('EMA_NONAME', 'Ihr Name konnte nicht korrekt entziffert werden. Die Nutzung des Planers ist daher nur unzureichend möglich und kann Fehler aufweisen.');
define('EMA_OFFICE', 'Meldestelle');
define('EMA_REGISTER','Registerauskunft');
define('EMA_REGISTER_NEW','Bürgerregister (neu)');
define('EMA_OFFICE_TITLE','Computergestützte Selbstauskunft');
define('EMA_OFFICE_INFO','Für eine genaue Planung und zum Schutz aller Bürger ist die Verfügbarkeit eines jeden sehr wichtig. Bitte geben Sie hier Ihre An- bzw. Abwesenheit für die nächsten Tage an. Die Eintragung erfolgt stundengenau.');
define('EMA_OFFICE_TUTORIAL','<h4 style="cursor:pointer;" onclick="$(\'.ema-tut\').toggleClass(\'hideme\');"><span style="float:right;font-weight:normal;font-style:italic;">Klicken zum Ein-/Ausblenden</span>Kurzanleitung</h4><p class="ema-tut hideme">Dieses Register dient der Datensammlung bezüglich der Online-Stati aller Mitbürger Deiner Stadt. Es entsteht eine Übersicht, wann welcher Bürger online sein wird, was besonders für die Expeditionsplanung nützlich ist, man denke da nur an die Vereinbarung von Treff-"Zeiten" zur Einnahme von Drogen bzw. Alkohol. Auch die Einschätzung, ob ein Bürger kurz vor dem Angriff noch online kommen wird, wird ermöglicht und erlaubt die Koordination von rettenden Heldenmaßnahmen.</p><p class="ema-tut hideme">Durch die Eingabe Deines eigenen Status\' bzw. Deines Lunchpakets gibst Du den anderen Bürgern einen Einblick, was mit Dir an dem entsprechenden tag anzufangen ist bzw. wieviele AP und KP Du mitbringst.</p><p class="ema-tut hideme">Die farbigen Boxen darunter sollen die Zeitschiene für einen Tag darstellen. Der Tag ist hier in 24 Stunden eingeteilt, wobei jede Stunde eine eigene Spalte ausmacht. In jeder Spalte finden sich vier Kästchen, welche durch Anklicken aktiviert werden. Rot bedeutet, dass Du in dieser Stunde gar nicht online sein wirst, Gelb steht für Zeiten, in denen Du unregelmäßig mal reinschauen kannst und Grün markiert Deine aktiven Stunden, in denen Du quasi in DV lebst. Die oberste, nicht eingefärbte Box (Standardeinstellung) zeigt Zeiten an, für die Du noch keine Aussage treffen kannst.</p><p class="ema-tut hideme">Eine Einstellung kann auch als Standard gespeichert und jederzeit wieder geladen werden. Für Bürger mit Farbschwächen, gibt es eine Symbolansicht, die mit dem Link unterhalb der Zeitschiene aktiviert werden kann.</p>');
define('EMA_FORM_DAY','Angaben für Tag');
define('EMA_S_THIRSTY','durstig');
define('EMA_S_HANGOVER','verkatert');
define('EMA_S_TERRORIZED','Angststarre');
define('EMA_S_CLEAN','clean');
define('EMA_S_TOPFORM','Top in Form');
define('EMA_S_SAFE','Panzerschrank');
define('EMA_CARE','Lunchpaket besteht aus');
define('EMA_S_WATER','Wasser (6 AP)');
define('EMA_S_FOOD_DEFOE','Normales Essen (6 AP)');
define('EMA_S_FOOD_YUMMY','Leckeres Essen (7 AP)');
define('EMA_S_STEROID','Steroide (6 AP)');
define('EMA_S_TWINOID','Twinoid (8 AP)');
define('EMA_S_ALCOHOL','Alkohol (6 AP)');
define('EMA_S_COFFEE','Kaffee (4 AP)');
define('EMA_S_ALARM','Wecker (1 AP)');
define('EMA_S_GAMBLE','Glücksspiel (1 AP)');
define('EMA_S_SIESTA','Ruheecke (2 AP)');
define('EMA_S_2NDLUNG','Zweite Lunge (6 AP)');
define('EMA_LIST','Übersichtsliste');
define('EMA_REGISTER_INFO','Die fleißigen Mitarbeiterinnen protokollieren die Zustände und Aufenthaltsorte der Bürger. Eine von ihnen hängt gerade eine aktualisierte Liste an die Eingangstür.');
define('DC1','Dehydriert');
define('DC2','Selbstmord durch Erhängen');
define('DC3','Selbstmord durch Zyanid');
define('DC4','Volksjustiz (Tod durch Erhängen)');
define('DC5','In der Außenwelt verschwunden');
define('DC6','Beim gestrigen Angriff aufgefressen');
define('DC7','Tod durch Entzug');
define('DC8','Tod durch Infektion');
define('DC9','Kopfschuss (Account von Admin gelöscht)');
define('DC10','Seele aufgelöst (Account gelöscht)');
define('DC11','Vergiftet');
define('DC12','Vom Ghul gefressen');
define('DC13','Aggression (Ghul)');
define('DC14','Verhungerter Ghul');
define('DC0','Todesursache unbekannt');
define('EMA_T_NONE','keine Angabe');
define('EMA_T_NOT','nicht online');
define('EMA_T_SPORA','sporadisch online');
define('EMA_T_ACTIV','aktiv online');
define('EMA_B_WATER','AP durch Wasser');
define('EMA_B_FOOD','AP durch Essen');
define('EMA_B_STEROID','AP durch Steroide');
define('EMA_B_TWINOID','AP durch Twinoid');
define('EMA_B_ALCOHOL','AP durch Alkohol');
define('EMA_B_COFFEE','AP durch Kaffee');
define('EMA_B_ALARM','AP durch Kreischenden Wecker');
define('EMA_B_GAMBLE','AP durch Glücksspiel');
define('EMA_B_SIESTA','AP durch Ruheecke');
define('EMA_B_2NDLUNG','AP durch Zweite Lunge');
define('EMA_TOGGLE_CODES', 'Verfügbarkeitssymbole ein- bzw. ausblenden');
define('CADAVER_GARBAGED', 'Leiche entsorgt');
define('CADAVER_SPRINKLED', 'Mit Wasser übergossen');
define('BY','von');
define('HOURS','Uhr');
define('LOC_ATDOOR','am Stadttor');
define('LOC_INTOWN','in der Stadt');
define('EEO','Alle Angaben ohne Gewehr.');
define('OWN_STATUS','Eigener Status');

# map
define('ZONE_D_0','Sichere Zone');
define('ZONE_D_1','Einzelner Zombie');
define('ZONE_D_2','Zombiemeute');
define('ZONE_D_3','Zombiehorde');
define('ZONE_D_4','Ganz viele Zombies');
define('ZONE_DIG','Es müssen noch <strong>%d</strong> Haufen entfernt werden.');
define('COORDS','Koordinaten');
define('ZONE_DRIED','Diese Zone ist <strong>leer</strong>.');
define('BUILDING_DRIED','Dieses Gebäude ist <strong>leer</strong>.');
define('ZONE_DANGER','Gefahrenstufe');
define('ZONE_NYV','Noch nie besucht');
define('ZONE_NVT','Heute noch nicht besucht');
define('ZONE_LASTUPDATE','Letztes Update');
define('ZONE_LASTVISIT','Letzter Besuch');
define('ZONE_LASTRADAR','Letzte Radarmeldung');
define('SCOUT_INFO','Aufklärung');
define('ZONE_ITEMSONGROUND','Gegenstände auf dem Boden');
define('MAP_OP_TITLE','Zonendetails');
define('MAP_OP_INFO','Zoneninfo');
define('MAP_OP_STORM','Sturm');
define('MAP_OP_SEARCH','Suche');
define('MAP_OP_SETTINGS','Optionen');
define('MAP_OP_EXPEDITIONS','Expeditionen');
define('MAP_LAYER_ZCORI','Zombies (Originale DV-Farben)');
define('MAP_LAYER_ZCDET','Zombies (Detailfarben)');
define('MAP_LAYER_CITCOUNT','Bürgerzahlen (Farben)');
define('MAP_LAYER_ZOMCOUNT','Zombiezahlen');
define('MAP_LAYER_ZONEMARKER','Zonenmarker');
define('MAP_DIRECTIONS','Himmelsrichtungen');
define('MAP_LAYER_DIRCOLOR','Farboverlay');
define('MAP_LAYER_DIRBORDER','Grenzen');
define('MAP_LAYER_WATCHTOWER','Wachturmbonus (Farben)');
define('MAP_LAYER_SEARCH','Suchergebnisse');
define('MAP_LAYER_VG','(potentielle) Verteidigungsgegenstände');
define('MAP_SEARCH_CAT','Kategorie wählen oder');
define('MAP_SEARCH_ITEM','Item eingeben');
define('MAP_SEARCH_FIND','Finden!');
define('MAP_LEGEND','Legende');
define('MAP_ALL_EXPEDITIONS','Alle Expeditionen');
define('MAP_SEARCH_TOGGLE_VIEW','Ansicht wechseln');
define('MAP_SEARCH_TOGGLE_INFO','Zwischen normaler Ansicht und Code für das Stadtforum wechseln');
define('MAP_SEARCH_ITEM_FOUND','%s gefunden auf');
define('ZONE_INFO_ASOF','Info von');
define('MAP_SEARCH_ITEM_NOT_FOUND','Leider konnte keine Zone mit %s gefunden werden.');
define('MAP_SEARCH_AJAXCOMPLETE','Meinst Du ...');
define('MAP_SEARCH_RUNNING','Suche nach %s läuft ...');
define('MAP_SEARCH_NOTHING_FOUND','Nix passendes gefunden.');
define('MAP_SEARCH_SHORT_TERM','Bitte mindestens drei Buchstaben eingeben.');
define('ZONE_REGENERATED','Zone ist regeneriert.');
define('ZONE_NEW_REGENERATED','Zone ist unberührt (und voll).');
define('ZONE_NOT_REGENERATED','Zone ist <em>nicht</em> regeneriert.');
define('ZONE_RADAR_INFO','Zoneninfo laut Radar');
define('WATCHTOWER','Wachturm');
define('VISION','Erinnerung eines Bürgers');
define('MAP_COLOR_BACK','Zoneneinfärbung');
define('NO_BACKCOLOR','Keine Hintergrundfarbe');
define('MAP_RADIUS','Radien');
define('MAP_INFOLAYER','Verschiedenes');
define('MAP_SEARCHFORM','Suche auf der Karte');
define('MAP_LAYER_VISITSTATUS','Besuchsstatus');
define('MAP_LAYER_CITIDOT','Bürger als Punkte');
define('MAP_LAYER_HUMCOUNT','Bürgerzahlen');
define('MAP_LAYER_WATCHTOWER1','Wachturmbonus Stufe 4');
define('MAP_LAYER_WATCHTOWER2','Wachturmbonus Stufe 5');
define('MAP_LAYER_RADIUS6','6AP-Radius');
define('MAP_LAYER_RADIUS9','9AP-Radius');
define('MAP_LAYER_RADIUS15','11km-Radius');
define('MAP_LAYER_REGENSTATUS','Zonenstatus (leer?)');
define('MAP_LAYER_REGENERATION','Buddlerradar');
define('LAST_OFFICIAL_COUNT','Letzte behördlich bestätigte Zählung');
define('EDIT_ZONE_INFO','Zoneninformation bearbeiten');
define('REGISTER_STORM','Sturmrichtung eintragen');
define('STORM_LOG','Sturmlogbuch');
define('DESERT','Wüste');
define('M_BUILDING_REGENERATED','Gebäude <strong>regeneriert</strong>');
define('M_ZONE_REGENERATED','Zone <strong>regeneriert</strong>');
define('M_BUILDING_DEPLETED','Gebäude <strong>leer</strong>');
define('M_ZONE_DEPLETED','Zone <strong>leer</strong>');
define('M_ZONE_DIG','Schutthaufen: <strong>%d</strong>');
define('LOGBOOK','Logbuch');

# travel
define('Ngo','NORDEN (oben)');
define('Wgo','WESTEN (links)');
define('Sgo','SÜDEN (unten)');
define('Ego','OSTEN (rechts)');
define('TRAVEL_TITLE','Reisebüro');
define('TRAVEL_INFO','Für gelangweilte Stadtbewohner bieten wir ungeführte Ausflüge in die Wüste an. In Ermangelung geeigneter Fahrzeuge sind derzeit nur Exkursionen per pedes im Angebot.');
define('TRAVEL_YOUR_GROUP','Deine Reisegruppe');
define('TRAVEL_NO_GROUP','Du gehörst noch keiner Reisegruppe an. Gründe eine neue Gruppe oder lass Dich von einer anderen Gruppe hinzufügen.');
define('TRAVEL_GROUP_NAME','Gruppenname');
define('TRAVEL_NEW_GROUP_NAME','s Reisegruppe');
define('TRAVEL_GROUP_PERSISTENT','Gruppe dauerhaft speichern');
define('TRAVEL_GROUP_ROUTE','Laufroute');
define('TRAVEL_GROUP_CREATE','Reisegruppe gründen');
define('TRAVEL_GROUP_NO_MEMBERS','Du hast die Teilnehmer Deiner Reisegruppe noch nicht definiert.');
define('TRAVEL_GROUP_MEMBERS','Teilnehmer');
define('TRAVEL_GROUP_UPDATE','Reisegruppe aktualisieren');
define('TRAVEL_GROUP_LEAVE','Reisegruppe verlassen');
define('TRAVEL_GROUP_CLOSE','Reisegruppe auflösen');
define('TRAVEL_YOUR_LOCATION','Aktueller Standort');
define('TRAVEL_ROUTE_PROGRESS','Das ist Punkt Nummer %n auf der Route (%p% geschafft).');
define('TRAVEL_ROUTE_AWAY','Du bist von der Route abgewichen.');
define('TRAVEL_ROUTE_NEXT','Die nächste Zone liegt im <span style="font-weight:bold;color:#090;">%s</span>.');
define('TRAVEL_ROUTE_MAX_ZOMBIES','Auf der Route muss nach bestätigten Meldungen mit bis zu <span style="font-weight:bold;color:#f00;">%d Zombies</span> gerechnet werden.');
define('TRAVEL_ROUTE_ITEMS','Unterwegs liegen diese Objekte herum');
define('TRAVEL_ALL_GROUPS','Alle für heute angemeldeten Reisegruppen');
define('TRAVEL_CHAOS','Die Mitarbeiterinnen des Reisebüros sind in Panik geflohen. Die Büroräume sehen verwüstet aus. Ein Windhauch pustet eines der gelben Klebezettelchen von einem Monitor in Deine Richtung. Mit zittriger Hand wurde darauf eine kurze Notiz gekritzelt:<br/><br/><em>"Marie, ich liebe Dich! Aber ich hau jetzt ab..."</em><br/><br/>Während Du Dich noch fragst, wer Marie wohl war, hörst Du draußen Raben krächzen. Vielleicht solltest Du Dich auch auf den Weg machen.');

define('RB_TRAVEL','Reisebüro');
define('RB_RUINS','Sehenswürdigkeiten');
define('RB_RUINS_SUB','Informationen aus dem Archäologischen Archiv - Chefarchivar <em>redsilence</em>');
define('RBR_STATUS','Erkundungsstatus:');
define('R_BUILDING_REGENERATED','Gebäude <strong>durchsuchbar</strong>');
define('R_BUILDING_DEPLETED','Gebäude <strong>leer</strong>');


# radar
define('RADAR_ERROR','Es ist ein Fehler aufgetreten, die Radardaten konnten nicht gespeichert werden.');
define('RADAR_BANNED','Die Informationen sind unglaubwürdig. Die Daten wurden nicht übertragen.');
define('RADAR_SCOUT','Die Zombieschätzungen wurden ins Oval Office übertragen. Gutes Auge, Aufklärer!');
define('RADAR_SCAVENGER','Der Regenerationsstatus der angrenzenden Felder wurde übertragen. Buddler FTW!');
define('RADAR_GUARDIAN','Spiel nicht an der Maschine herum, Wächter. Du sollst aufpassen!');
define('RADAR_CITIZEN','Überlass die Radarfunktion den Helden, Bürger! Willst Du nicht weiter graben?');
define('RADAR_TAMER','Hat Dein Hund schon wieder auf das Funkgerät gepinkelt? Geh Gassi!');

# stats
define('STATS_DEFOE5','S5 Normal');
define('STATS_HARD5','S5 Hardcore');
define('STATS_DEFOE4','S4 Normal');
define('STATS_HARD4','S4 Hardcore');
define('STATS_DEFOE3','S3 Normal');
define('STATS_HARD3','S3 Hardcore');
define('STAT_ZOMBIE_TITLE','Zombieangriffe');
define('STAT_ZOMBIE_TITLE_S4','Zombieangriffe');
define('STAT_ZOMBIE_TITLE_S3','ZA Saison 3');
define('STAT_SOULS_TITLE','Seelenpunkte');
define('STAT_REWARDS_TITLE','Auszeichnungen');
define('STAT_TITLES_TITLE','Titel');
define('STAT_ACTIVETOWNS_TITLE','Aktive Städte');
define('STAT_OLDTOWNS_TITLE','Alte Städte');
define('STAT_SCOUTS_TITLE','Aufklärer');
define('STAT_ZOMBIE_INFO','Ein Schild am Eingang weist den Besucher darauf hin, dass die Raumgestaltung wegen des versehentlichen Explodierens einer Schießpulverbombe bitte nicht beachtet werden soll. Die Aufräumarbeiten sind im Gange. Dennoch soll der Service genutzt werden können. Leider sieht man außer einem alten Ausdruck nicht viel.</p><p>Als Du näher an die Pinwand herantritts, siehst Du, dass der Ausdruck kompliziert gefaltet ist. Wenn Du einen Zeileneintrag berührst, klappt eine Grafik heraus.');
define('STAT_ZOMBIE_BASE','Daten zu Zombieangriffen - %d Datensätze aus %s Städten');
define('DEATH_CALC','Todesrechner <em>von haase</em>');
define('DEATH_CALC_ZOMBIES','Zombies dringen ein');
define('DEATH_CALC_CITIZENS','Bürger in der Stadt');
define('DEATH_CALC_PERSDEF','persönliche Verteidigung');
define('DEATH_CALCULATE','Wie stehen meine Chancen?');
define('MIN','Minimum');
define('MAX','Maximum');
define('AVG','Mittelwert');
define('MED','Median');
define('COUNT_DATASETS','Anzahl Datensätze');
define('YOUR_CITY','Deine Stadt');
define('GOOD_LUCK','Viel Glück!');
define('STAT_ACTIVETOWNS_INFO','Sowohl die Liste der aktiven als auch die der alten Städte berücksichtigt nur Daten ab dem Start der dritten Saison (21.02.2011). Die ausgegrauten Zeilen zeigen an, dass diese Daten von gestern stammen und die Stadt dementsprechend schon tot sein könnte.');
define('STAT_OLDTOWNS_INFO','Zu den <em>Alten Städten</em> gehören Städte, von denen sich weder gestern noch heute nicht wenigstens ein Spieler hier eingeloggt hat.');
define('STAT_CITY_NAME','Name der Stadt');
define('STAT_LAST_DAY','Überlebte Tage');
define('STAT_CHAOS','Chaos');
define('STAT_DEVAST','Verwüstet');
define('STAT_CHAOS_X','Es herrscht Chaos!');
define('STAT_DEVAST_X','Die Stadt wurde zerstört!');
define('STAT_SURVIVORS','Überlebende');
define('STAT_WATER_WELL','Brunnenwasser');
define('STAT_WATER_BANK','Wasser in der Bank');
define('STAT_JERRY_BANK','Kanister in der Bank');
define('STAT_DEF_ITEMS','Anzahl Verteidigungsgegenstände');
define('STAT_LAST_ZOMBIES','Anzahl Zombies beim letzten Angriff');
define('STAT_LAST_DEF','Stadtverteidigung beim letzten Angriff');
define('STAT_LAST_UPDATE','Letzte Aktualisierung');
define('SHOW_ONLY_OWN_TOWNS','Nur meine Städte anzeigen');
define('SHOW_ONLY_TOWNS_WITH','Nur Städte anzeigen mit mindestens');
define('SHOW_DEFOE_TOWNS','Normale Städte anzeigen');
define('SHOW_HARD_TOWNS','Pandämonium-Städte anzeigen');
define('SHOW_INTERPOLATED_TOWNS','Städte anzeigen, die heute noch nicht aktualisiert wurden');
define('STAT_MAP_SIZE','Kartengröße');
define('SURVIVORS','Überlebende');
define('BUILDINGS','Gebäude');
define('DEFENSIVE_OBJECTS','Vert.-gegenstände');
define('MAP','Karte');
define('ATTACKS','Angriffe');
define('CADAVER','Kadaver');
define('LAST_ATTACK','Gestriger Angriff');
define('NEXT_ATTACK','Heutiger Angriff');
define('REWARDS','Auszeichnungen');
define('TITLES','Titel');
define('OBTAINABLE','erhältlich ab');
define('SOUL_POINTS', 'Seelenpunkte');
define('POINTS', 'Punkte');
define('GAMES', 'Stadthistorie');
define('NO_DATA_AVAILABLE', 'Keine Daten verfügbar.');
define('RANKINGPOINTS', 'Aktuelle Punktzahl basierend auf den letzten Daten: %r Überlebende und %d Tote. Diese Schätzung ist ungenau!');
define('YOU_WILL_SURVIVE', 'Die Wahrscheinlichkeit, den nächsten Angriff zu überleben, liegt bei ');
define('ZOMBIE_SPREAD','Verteilung der Zombieangriffe an Tag ');

# toolbox
define('ADD','Hinzufügen');
define('SAVE','Speichern');
define('EXPLORATION_LEVEL','Erkundungsstufe');

# new
define('CITIZENS_OUTSIDE','Einwohner in der Außenwelt');
define('TEMPORARY','davon temporär');

# records
define('STAT_RECORDS_TITLE','Rekorde');
define('STAT_RECORDS_INFO','Anzeige von registrierten Rekorden. Ergänzungsvorschlag? Bitte im Saloon posten.');
define('REC_ZOMBIE_COUNT','Höchster registrierter Zombieangriff');
define('REC_DEFENSE','Höchste registrierte Verteidigung');
define('REC_DEFENSE_10','Höchste registrierte Verteidigung (inkl. 10000 Bonus)');
define('REC_DEFENSE_15','Höchste registrierte Verteidigung (inkl. 15000 Bonus)');
define('HOSPITAL','Verlassenes Hospital');
define('HOTEL','Verlassenes Hotel');
define('BUNKER','Verlassener Bunker');
define('DISTANCE','Entfernung');
define('RUIN_DISTANCES','Entfernungen begehbarer Ruinen');
