INSERT INTO `dvoo_items` VALUES (35, 'Padlock and Chain', 'lock', 'Furniture');
INSERT INTO `dvoo_items` VALUES (184, 'Kwik-Fix', 'repair_one', 'Misc');
INSERT INTO `dvoo_items` VALUES (147, 'Mouldy Ham Sandwich', 'food_sandw', 'Food');
INSERT INTO `dvoo_items` VALUES (161, 'Scrap Metal', 'metal_bad', 'Rsc');
INSERT INTO `dvoo_items` VALUES (89, 'Twinoid 500mg', 'drug_hero', 'Drug');
INSERT INTO `dvoo_items` VALUES (96, 'Sheet Metal (parts)', 'plate_raw', 'Misc');
INSERT INTO `dvoo_items` VALUES (101, 'Electronic component', 'electro', 'Rsc');
INSERT INTO `dvoo_items` VALUES (69, 'Vodka Marinostov', 'vodka', 'Food');
INSERT INTO `dvoo_items` VALUES (90, 'Chest', 'chest', 'Box');
INSERT INTO `dvoo_items` VALUES (162, 'Rotting Log', 'wood_bad', 'Rsc');
INSERT INTO `dvoo_items` VALUES (59, 'Twisted Plank', 'wood2', 'Rsc');
INSERT INTO `dvoo_items` VALUES (73, 'Semtex', 'explo', 'Rsc');
INSERT INTO `dvoo_items` VALUES (132, 'Compact Detonator', 'deto', 'Rsc');
INSERT INTO `dvoo_items` VALUES (60, 'Wrought Iron', 'metal', 'Rsc');
INSERT INTO `dvoo_items` VALUES (43, 'Stinking Pig', 'pet_pig', 'Misc');
INSERT INTO `dvoo_items` VALUES (26, 'Box of Matches', 'lights', 'Misc');
INSERT INTO `dvoo_items` VALUES (103, 'Hydratone 100mg', 'drug_water', 'Drug');
INSERT INTO `dvoo_items` VALUES (110, 'Repair Kit', 'repair_kit', 'Misc');
INSERT INTO `dvoo_items` VALUES (157, 'Meaty Bone', 'bone_meat', 'Food');
INSERT INTO `dvoo_items` VALUES (234, 'Burnt out Torch', 'torch_off', 'Weapon');
INSERT INTO `dvoo_items` VALUES (134, 'Unshaped Concrete Blocks', 'concrete_wall', 'Armor');
INSERT INTO `dvoo_items` VALUES (104, 'Radio Cassette Player (no battery)', 'radio_off', 'Misc');
INSERT INTO `dvoo_items` VALUES (84, 'Copper Pipe', 'tube', 'Rsc');
INSERT INTO `dvoo_items` VALUES (3, 'Can', 'can', 'Food');
INSERT INTO `dvoo_items` VALUES (81, 'Duct Tape', 'rustine', 'Rsc');
INSERT INTO `dvoo_items` VALUES (2, 'Battery', 'pile', 'Rsc');
INSERT INTO `dvoo_items` VALUES (105, 'Radio Cassette Player ', 'radio_on', 'Furniture');
INSERT INTO `dvoo_items` VALUES (1, 'Water Ration', 'water', 'Food');
INSERT INTO `dvoo_items` VALUES (159, 'Patchwork Beam', 'wood_beam', 'Rsc');
INSERT INTO `dvoo_items` VALUES (136, 'Paracetoid 7g', 'disinfect', 'Drug');
INSERT INTO `dvoo_items` VALUES (41, 'Handful of nuts and bolts', 'meca_parts', 'Rsc');
INSERT INTO `dvoo_items` VALUES (95, 'Pharmaceutical Products', 'pharma', 'Drug');
INSERT INTO `dvoo_items` VALUES (92, 'Toolbox', 'chest_tools', 'Box');
INSERT INTO `dvoo_items` VALUES (158, 'Broken Human Bone', 'bone', 'Weapon');
INSERT INTO `dvoo_items` VALUES (299, 'Â« Pine Fresh Â» Smoke Bomb', 'smoke_bomb', 'Misc');
INSERT INTO `dvoo_items` VALUES (58, 'Full Jerrycan', 'jerrycan', 'Misc');
INSERT INTO `dvoo_items` VALUES (169, 'Trestle', 'trestle', 'Armor');
INSERT INTO `dvoo_items` VALUES (186, 'Old Washing Machine', 'machine_1', 'Furniture');
INSERT INTO `dvoo_items` VALUES (97, '''Wake The Dead''', 'rhum', 'Food');
INSERT INTO `dvoo_items` VALUES (173, 'Flash Powder', 'powder', 'Misc');
INSERT INTO `dvoo_items` VALUES (146, 'Stale Tart', 'food_tarte', 'Food');
INSERT INTO `dvoo_items` VALUES (160, 'Metal Support', 'metal_beam', 'Rsc');
INSERT INTO `dvoo_items` VALUES (117, 'Battery Launcher 1-ITF (empty)', 'pilegun_empty', 'Weapon');
INSERT INTO `dvoo_items` VALUES (76, 'Plastic Bag', 'grenade_empty', 'Weapon');
INSERT INTO `dvoo_items` VALUES (179, 'Solid Wooden Board', 'wood_plate', 'Armor');
INSERT INTO `dvoo_items` VALUES (119, 'EMS System (incomplete)', 'sport_elec_empty', 'Misc');
INSERT INTO `dvoo_items` VALUES (140, 'Packet of Soft Crisps', 'food_bar1', 'Food');
INSERT INTO `dvoo_items` VALUES (204, 'Wire Mesh', 'fence', 'Furniture');
INSERT INTO `dvoo_items` VALUES (165, 'Broken Electronic Device', 'electro_box', 'Rsc');
INSERT INTO `dvoo_items` VALUES (142, 'Dried Chewing Gum', 'food_bar3', 'Food');
INSERT INTO `dvoo_items` VALUES (31, 'Mattress', 'bed', 'Armor');
INSERT INTO `dvoo_items` VALUES (137, 'Ness-Quick Weedkiller', 'digger', 'Misc');
INSERT INTO `dvoo_items` VALUES (107, 'Old Door', 'door', 'Armor');
INSERT INTO `dvoo_items` VALUES (168, 'Mechanism', 'mecanism', 'Rsc');
INSERT INTO `dvoo_items` VALUES (38, 'Dice', 'dice', 'Misc');
INSERT INTO `dvoo_items` VALUES (133, 'Bag of Cement', 'concrete', 'Misc');
INSERT INTO `dvoo_items` VALUES (210, 'Opened packet of Cigarettes', 'cigs', 'Misc');
INSERT INTO `dvoo_items` VALUES (171, 'Water Purifying Tablets', 'water_cleaner', 'Drug');
INSERT INTO `dvoo_items` VALUES (235, 'Dried Marshmallows', 'chama', 'Food');
INSERT INTO `dvoo_items` VALUES (196, 'Rusty Chain', 'chain', 'Weapon');
INSERT INTO `dvoo_items` VALUES (166, 'Flatpacked Furniture', 'deco_box', 'Misc');
INSERT INTO `dvoo_items` VALUES (15, 'Staff', 'staff', 'Weapon');
INSERT INTO `dvoo_items` VALUES (22, 'Shopping Trolley', 'cart', 'Box');
INSERT INTO `dvoo_items` VALUES (125, 'Radius Radar Beacon', 'tagger', 'Misc');
INSERT INTO `dvoo_items` VALUES (149, 'Strong Spices', 'spices', 'Misc');
INSERT INTO `dvoo_items` VALUES (23, 'Can Opener', 'can_opener', 'Weapon');
INSERT INTO `dvoo_items` VALUES (64, 'Sheet Metal', 'plate', 'Armor');
INSERT INTO `dvoo_items` VALUES (47, 'Huge Snake (Ophiophagus trouser)', 'pet_snake', 'Misc');
INSERT INTO `dvoo_items` VALUES (44, 'Giant Rat', 'pet_rat', 'Misc');
INSERT INTO `dvoo_items` VALUES (188, 'Beer Fridge', 'machine_3', 'Furniture');
INSERT INTO `dvoo_items` VALUES (28, 'Valium Shot', 'xanax', 'Drug');
INSERT INTO `dvoo_items` VALUES (18, 'Pathetic Penknife', 'small_knife', 'Weapon');
INSERT INTO `dvoo_items` VALUES (14, 'Screwdriver', 'screw', 'Weapon');
INSERT INTO `dvoo_items` VALUES (138, 'Food Parcel', 'chest_food', 'Food');
INSERT INTO `dvoo_items` VALUES (145, 'Out-of-Date Biscuits', 'food_pims', 'Food');
INSERT INTO `dvoo_items` VALUES (148, 'Chinese Noodles', 'food_noodles', 'Food');
INSERT INTO `dvoo_items` VALUES (13, 'Adjustable Spanner', 'wrench', 'Weapon');
INSERT INTO `dvoo_items` VALUES (163, 'Hacksaw', 'saw_tool', 'Misc');
INSERT INTO `dvoo_items` VALUES (40, 'Belt', 'courroie', 'Rsc');
INSERT INTO `dvoo_items` VALUES (20, 'Box Cutter', 'cutter', 'Weapon');
INSERT INTO `dvoo_items` VALUES (141, 'Mouldy Neapolitan', 'food_bar2', 'Food');
INSERT INTO `dvoo_items` VALUES (4, 'Open Can', 'can_open', 'Food');
INSERT INTO `dvoo_items` VALUES (144, 'Half-eaten Chicken Wings', 'food_chick', 'Food');
INSERT INTO `dvoo_items` VALUES (52, 'Tasty-looking Steak', 'meat', 'Food');
INSERT INTO `dvoo_items` VALUES (5, 'Battery Launcher 1-ITF (loaded)', 'pilegun', 'Weapon');
INSERT INTO `dvoo_items` VALUES (187, 'Carcinogenic Oven', 'machine_2', 'Furniture');
INSERT INTO `dvoo_items` VALUES (25, 'Manbag', 'bag', 'Box');
INSERT INTO `dvoo_items` VALUES (16, 'Serrated Knife', 'knife', 'Weapon');
INSERT INTO `dvoo_items` VALUES (39, 'Engine', 'engine', 'Misc');
INSERT INTO `dvoo_items` VALUES (111, 'Water Pistol (empty)', 'watergun_empty', 'Weapon');
INSERT INTO `dvoo_items` VALUES (108, 'Suspicious-looking Vegetable', 'vegetable', 'Food');
INSERT INTO `dvoo_items` VALUES (48, 'Pocket Vibrator (charged)', 'vibr', 'Misc');
INSERT INTO `dvoo_items` VALUES (153, 'Aqua-Splash (incomplete)', 'watergun_opt_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (42, 'Chicken', 'pet_chick', 'Misc');
INSERT INTO `dvoo_items` VALUES (32, 'Bedside Lamp (off)', 'lamp', 'Furniture');
INSERT INTO `dvoo_items` VALUES (66, 'Bandage', 'bandage', 'Drug');
INSERT INTO `dvoo_items` VALUES (143, 'Rancid Jaffa Cakes', 'food_biscuit', 'Food');
INSERT INTO `dvoo_items` VALUES (181, 'Tool Bag', 'repair_kit_part_raw', 'Misc');
INSERT INTO `dvoo_items` VALUES (231, 'Sheet of Plywood', 'out_def', 'Misc');
INSERT INTO `dvoo_items` VALUES (124, 'Devastator (incomplete)', 'big_pgun_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (135, 'Unlabelled Drug', 'drug_random', 'Drug');
INSERT INTO `dvoo_items` VALUES (151, 'Incomplete Deck of Cards', 'cards', 'Misc');
INSERT INTO `dvoo_items` VALUES (51, 'Anabolic Steroids', 'drug', 'Drug');
INSERT INTO `dvoo_items` VALUES (120, 'EMS System (charged)', 'sport_elec', 'Misc');
INSERT INTO `dvoo_items` VALUES (17, 'Machete', 'cutcut', 'Weapon');
INSERT INTO `dvoo_items` VALUES (208, 'Aqua-Splash (5 shots)', 'watergun_opt_5', 'Weapon');
INSERT INTO `dvoo_items` VALUES (100, 'Incomplete CafetiÃ¨re', 'coffee_machine_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (154, 'Pocket Vibrator (incomplete)', 'vibr_empty', 'Misc');
INSERT INTO `dvoo_items` VALUES (53, 'Unspecified Meat', 'undef', 'Food');
INSERT INTO `dvoo_items` VALUES (170, 'JÃ¤rpen Table', 'table', 'Armor');
INSERT INTO `dvoo_items` VALUES (112, 'Aqua-Splash (3 shots)', 'watergun_opt_3', 'Weapon');
INSERT INTO `dvoo_items` VALUES (109, 'Repair Kit (damaged)', 'repair_kit_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (123, 'Devastator (loaded)', 'big_pgun', 'Weapon');
INSERT INTO `dvoo_items` VALUES (185, 'Engine (incomplete)', 'engine_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (150, 'Spicy Chinese Noodles', 'food_noodles_hot', 'Food');
INSERT INTO `dvoo_items` VALUES (233, 'Torch', 'torch', 'Armor');
INSERT INTO `dvoo_items` VALUES (122, 'Devastator (empty)', 'big_pgun_empty', 'Weapon');
INSERT INTO `dvoo_items` VALUES (74, 'Human flesh', 'hmeat', 'Food');
INSERT INTO `dvoo_items` VALUES (139, 'Doggybag', 'food_bag', 'Food');
INSERT INTO `dvoo_items` VALUES (129, 'Gun', 'gun', 'Furniture');
INSERT INTO `dvoo_items` VALUES (130, 'Machine Gun', 'machine_gun', 'Furniture');
INSERT INTO `dvoo_items` VALUES (172, 'Intestine Melon', 'vegetable_tasty', 'Food');
INSERT INTO `dvoo_items` VALUES (205, 'Water Pistol (3 shots)', 'watergun_3', 'Weapon');
INSERT INTO `dvoo_items` VALUES (287, 'Festering Flesh', 'smelly_meat', 'Misc');
INSERT INTO `dvoo_items` VALUES (178, 'Crate Lid', 'wood_plate_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (174, 'Flash Grenade', 'flash', 'Misc');
INSERT INTO `dvoo_items` VALUES (207, 'Water Pistol (1 shot)', 'watergun_1', 'Weapon');
INSERT INTO `dvoo_items` VALUES (245, 'Water Cooler Bottle (empty)', 'water_can_empty', 'Misc');
INSERT INTO `dvoo_items` VALUES (99, 'CafetiÃ¨re', 'coffee_machine', 'Furniture');
INSERT INTO `dvoo_items` VALUES (80, 'Incomplete Whisk', 'mixergun_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (29, 'Rocking Chair', 'chair', 'Furniture');
INSERT INTO `dvoo_items` VALUES (128, 'Ektorp-Gluten Chair', 'chair_basic', 'Furniture');
INSERT INTO `dvoo_items` VALUES (167, 'Broken Hacksaw', 'saw_tool_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (200, 'Boxes', 'home_box', 'Furniture');
INSERT INTO `dvoo_items` VALUES (218, 'Car Door', 'car_door', 'Armor');
INSERT INTO `dvoo_items` VALUES (211, 'PUTA Mark II Calibrator', 'pilegun_upkit', 'Misc');
INSERT INTO `dvoo_items` VALUES (54, 'Groundsheet', 'sheet', 'Misc');
INSERT INTO `dvoo_items` VALUES (250, 'Betapropine 5mg (expired)', 'beta_drug_bad', 'Drug');
INSERT INTO `dvoo_items` VALUES (11, 'Lawnmower', 'lawn', 'Weapon');
INSERT INTO `dvoo_items` VALUES (198, 'Tasty Homemade Dish', 'dish_tasty', 'Food');
INSERT INTO `dvoo_items` VALUES (19, 'Swiss Army Knife', 'swiss_knife', 'Weapon');
INSERT INTO `dvoo_items` VALUES (98, 'Bloody hot coffee', 'coffee', 'Food');
INSERT INTO `dvoo_items` VALUES (243, 'Safe', 'safe', 'Box');
INSERT INTO `dvoo_items` VALUES (106, 'Cyanide', 'cyanure', 'Drug');
INSERT INTO `dvoo_items` VALUES (201, 'Makeshift Barricade', 'home_def', 'Furniture');
INSERT INTO `dvoo_items` VALUES (212, 'Battery Launcher Mk. II (empty)', 'pilegun_up_empty', 'Weapon');
INSERT INTO `dvoo_items` VALUES (62, 'Water Bomb', 'grenade', 'Weapon');
INSERT INTO `dvoo_items` VALUES (180, 'Wad of Cash', 'money', 'Furniture');
INSERT INTO `dvoo_items` VALUES (85, 'Wonky Shopping Trolley', 'cart_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (182, 'Radius Mark II (incomplete)', 'radius_mk2_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (252, 'Fleshrooms', 'fruit_sub_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (79, 'Incomplete Chainsaw', 'chainsaw_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (257, 'Pound of Flesh', 'flesh_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (258, 'Grisly Bomb', 'flesh', 'Misc');
INSERT INTO `dvoo_items` VALUES (197, 'Dodgy Homemade Dish', 'dish', 'Food');
INSERT INTO `dvoo_items` VALUES (253, 'Sticky Pastry Ball', 'fruit_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (213, 'Battery Launcher Mk. II (loaded)', 'pilegun_up', 'Weapon');
INSERT INTO `dvoo_items` VALUES (242, 'PC Base Unit', 'pc', 'Furniture');
INSERT INTO `dvoo_items` VALUES (183, 'Radius Mark II', 'radius_mk2', 'Misc');
INSERT INTO `dvoo_items` VALUES (34, 'Mini HI-Fi (Broken)', 'music_part', 'Furniture');
INSERT INTO `dvoo_items` VALUES (206, 'Water Pistol (2 shots)', 'watergun_2', 'Weapon');
INSERT INTO `dvoo_items` VALUES (219, 'Car Door (incomplete)', 'car_door_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (8, 'Aqua-Splash (empty)', 'watergun_opt_empty', 'Weapon');
INSERT INTO `dvoo_items` VALUES (259, 'Thick Solution', 'pharma_part', 'Drug');
INSERT INTO `dvoo_items` VALUES (65, 'Jerrycan Pump (unattached)', 'jerrygun_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (118, 'Taser (incomplete)', 'taser_empty', 'Weapon');
INSERT INTO `dvoo_items` VALUES (78, 'Plastic Bag and Semtex', 'bgrenade_empty', 'Weapon');
INSERT INTO `dvoo_items` VALUES (214, 'Crushed Battery', 'pile_broken', 'Misc');
INSERT INTO `dvoo_items` VALUES (10, 'Chainsaw (loaded)', 'chainsaw', 'Weapon');
INSERT INTO `dvoo_items` VALUES (46, 'Fat Cat', 'pet_cat', 'Furniture');
INSERT INTO `dvoo_items` VALUES (246, 'Water Cooler Bottle (1 ration)', 'water_can_1', 'Food');
INSERT INTO `dvoo_items` VALUES (230, 'Handful of Sweets', 'food_candies', 'Food');
INSERT INTO `dvoo_items` VALUES (164, 'Quality Log', 'wood_log', 'Furniture');
INSERT INTO `dvoo_items` VALUES (216, 'Construction Kit', 'rsc_pack_2', 'Box');
INSERT INTO `dvoo_items` VALUES (88, 'Utility belt', 'pocket_belt', 'Box');
INSERT INTO `dvoo_items` VALUES (45, 'Guard Dog', 'pet_dog', 'Armor');
INSERT INTO `dvoo_items` VALUES (77, 'Exploding Water Bomb', 'bgrenade', 'Weapon');
INSERT INTO `dvoo_items` VALUES (199, 'Iron Chest', 'home_box_xl', 'Furniture');
INSERT INTO `dvoo_items` VALUES (115, 'Electric Whisk (incomplete)', 'mixergun_empty', 'Weapon');
INSERT INTO `dvoo_items` VALUES (248, 'Water Cooler Bottle (3 rations)', 'water_can_3', 'Food');
INSERT INTO `dvoo_items` VALUES (247, 'Water Cooler Bottle (2 rations)', 'water_can_2', 'Food');
INSERT INTO `dvoo_items` VALUES (223, 'Anabolic Steroids', 'drug', 'Drug');
INSERT INTO `dvoo_items` VALUES (236, 'Burnt Marshmallows', 'chama_tasty', 'Food');
INSERT INTO `dvoo_items` VALUES (70, 'Jerrycan Pump (empty)', 'jerrygun_off', 'Weapon');
INSERT INTO `dvoo_items` VALUES (221, 'Corrosive Liquid', 'poison_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (260, 'Fleshroom Puree', 'fruit', 'Food');
INSERT INTO `dvoo_items` VALUES (286, 'Mobile Phone', 'iphone', 'Weapon');
INSERT INTO `dvoo_items` VALUES (116, 'Chainsaw (incomplete)', 'chainsaw_empty', 'Weapon');
INSERT INTO `dvoo_items` VALUES (220, 'Vial of Poison', 'poison', 'Misc');
INSERT INTO `dvoo_items` VALUES (82, 'Dismantled Mower', 'lawn_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (113, 'Aqua-Splash (2 shots)', 'watergun_opt_2', 'Weapon');
INSERT INTO `dvoo_items` VALUES (102, 'Citizen''s Welcome Pack', 'chest_citizen', 'Box');
INSERT INTO `dvoo_items` VALUES (91, 'Large Chest', 'chest_xl', 'Box');
INSERT INTO `dvoo_items` VALUES (56, 'Ultra-Rucksack', 'bagxl', 'Box');
INSERT INTO `dvoo_items` VALUES (93, 'Bedside Lamp (on)', 'lamp_on', 'Furniture');
INSERT INTO `dvoo_items` VALUES (94, 'Mini HiFi (on)', 'music', 'Furniture');
INSERT INTO `dvoo_items` VALUES (9, 'Electric Whisk (charged)', 'mixergun', 'Weapon');
INSERT INTO `dvoo_items` VALUES (127, 'Jerrycan Gun (ready)', 'jerrygun', 'Weapon');
INSERT INTO `dvoo_items` VALUES (33, 'Persian Rug', 'carpet', 'Furniture');
INSERT INTO `dvoo_items` VALUES (152, 'Box of Games', 'game_box', 'Box');
INSERT INTO `dvoo_items` VALUES (36, 'Doormat', 'door_carpet', 'Furniture');
INSERT INTO `dvoo_items` VALUES (7, 'Taser', 'taser', 'Weapon');
INSERT INTO `dvoo_items` VALUES (265, 'Banned Citizen''s Note', 'banned_note', 'Misc');
INSERT INTO `dvoo_items` VALUES (114, 'Aqua-Splash (1 shot)', 'watergun_opt_1', 'Weapon');
INSERT INTO `dvoo_items` VALUES (203, 'Parcel', 'book_gen_box', 'Box');
INSERT INTO `dvoo_items` VALUES (261, 'Fleshroom Puree', 'fruit', 'Food');
INSERT INTO `dvoo_items` VALUES (263, 'Stagnant Water Can', 'water_cup_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (215, 'Construction Kit', 'rsc_pack_3', 'Box');
INSERT INTO `dvoo_items` VALUES (288, 'Unrecognisable Remains', 'broken', 'Misc');
INSERT INTO `dvoo_items` VALUES (224, 'Open Can', 'can_open', 'Food');
INSERT INTO `dvoo_items` VALUES (305, 'Construction Blueprint (common)', 'bplan_c', 'Misc');
INSERT INTO `dvoo_items` VALUES (306, 'Construction Blueprint (uncommon)', 'bplan_u', 'Misc');
INSERT INTO `dvoo_items` VALUES (314, 'Worn Leather Bag', 'bplan_drop', 'Misc');
INSERT INTO `dvoo_items` VALUES (222, 'Water Ration', 'water', 'Food');
INSERT INTO `dvoo_items` VALUES (281, 'SawdustSteak', 'woodsteak', 'Food');
INSERT INTO `dvoo_items` VALUES (191, 'Instruction Manual', 'rp_manual', 'Misc');
INSERT INTO `dvoo_items` VALUES (229, 'Lunch Box', 'food_armag', 'Box');
INSERT INTO `dvoo_items` VALUES (307, 'Construction Blueprint (rare)', 'bplan_r', 'Misc');
INSERT INTO `dvoo_items` VALUES (310, 'Sealed Architect''s Chest', 'bplan_box_e', 'Box');
INSERT INTO `dvoo_items` VALUES (309, 'Architect''s Chest', 'bplan_box', 'Box');
INSERT INTO `dvoo_items` VALUES (30, 'Dusty Book', 'rp_book', 'Misc');
INSERT INTO `dvoo_items` VALUES (217, 'Construction Kit', 'rsc_pack_1', 'Box');
INSERT INTO `dvoo_items` VALUES (311, 'Egg', 'egg', 'Food');
INSERT INTO `dvoo_items` VALUES (202, 'Envelope', 'book_gen_letter', 'Box');
INSERT INTO `dvoo_items` VALUES (209, 'Aqua-Splash (4 shots)', 'watergun_opt_4', 'Weapon');
INSERT INTO `dvoo_items` VALUES (264, 'Purified Stagnant Water', 'water_cup', 'Food');
INSERT INTO `dvoo_items` VALUES (175, 'Teddy Bear', 'teddy', 'Furniture');
INSERT INTO `dvoo_items` VALUES (313, 'Exploding Grapefruit', 'boomfruit', 'Weapon');
INSERT INTO `dvoo_items` VALUES (244, 'Encyclopedia', 'rp_twin', 'Misc');
INSERT INTO `dvoo_items` VALUES (262, 'Suspicious-looking Vegetable', 'vegetable', 'Food');
INSERT INTO `dvoo_items` VALUES (193, 'Illegible Notebook', 'rp_book2', 'Misc');
INSERT INTO `dvoo_items` VALUES (312, 'Apple', 'apple', 'Food');
INSERT INTO `dvoo_items` VALUES (308, 'Construction Blueprint (very rare!)', 'bplan_e', 'Misc');
INSERT INTO `dvoo_items` VALUES (194, 'Photo Album', 'rp_book', 'Misc');
INSERT INTO `dvoo_items` VALUES (324, 'Magnetic Key Blank', 'prints', 'Misc');
INSERT INTO `dvoo_items` VALUES (325, 'Bump Key Blank', 'prints', 'Misc');
INSERT INTO `dvoo_items` VALUES (326, 'Bottle Opener Blank', 'prints', 'Misc');
INSERT INTO `dvoo_items` VALUES (277, 'Cursed Cuddly Toy', 'teddy', 'Furniture');
INSERT INTO `dvoo_items` VALUES (322, 'Bump Key', 'bumpKey', 'Misc');
INSERT INTO `dvoo_items` VALUES (321, 'Magnetic Key', 'magneticKey', 'Misc');
INSERT INTO `dvoo_items` VALUES (323, 'Bottle Opener', 'classicKey', 'Misc');
INSERT INTO `dvoo_items` VALUES (126, 'Spy Rocket', 'flare', 'Misc');
INSERT INTO `dvoo_items` VALUES (270, 'Bloody Dressing', 'infect_poison_part', 'Misc');
INSERT INTO `dvoo_items` VALUES (227, 'Gift Parcel', 'postal_box', 'Box');
INSERT INTO `dvoo_items` VALUES (334, 'Construction Blueprint (uncommon)', 'bplan_u', 'Misc');
INSERT INTO `dvoo_items` VALUES (303, 'Sand Ball', 'sand_ball', 'Misc');
INSERT INTO `dvoo_items` VALUES (304, 'Jus de mirabelle suspect', 'omg_this_will_kill_you', 'Food');
INSERT INTO `dvoo_items` VALUES (189, 'A letter with no address', 'rp_letter', 'Misc');
INSERT INTO `dvoo_items` VALUES (331, 'Construction Blueprint (uncommon)', 'bplan_u', 'Misc');
INSERT INTO `dvoo_items` VALUES (335, 'Construction Blueprint (rare)', 'bplan_r', 'Misc');
INSERT INTO `dvoo_items` VALUES (332, 'Construction Blueprint (rare)', 'bplan_r', 'Misc');
INSERT INTO `dvoo_items` VALUES (190, 'Scroll', 'rp_scroll', 'Misc');
INSERT INTO `dvoo_items` VALUES (328, 'Construction Blueprint (uncommon)', 'bplan_u', 'Misc');
INSERT INTO `dvoo_items` VALUES (271, 'Toxin', 'infect_poison', 'Misc');
INSERT INTO `dvoo_items` VALUES (340, 'Hurling stick', 'hurling_stick', 'Weapon');
INSERT INTO `dvoo_items` VALUES (339, 'Winness', 'guiness', 'Food');
INSERT INTO `dvoo_items` VALUES (338, 'Green Imp Suit', 'leprechaun_suit', 'Misc');
INSERT INTO `dvoo_items` VALUES (273, 'Anabolic Steroids', 'drug', 'Drug');
INSERT INTO `dvoo_items` VALUES (351, 'Aimless Soul', 'soul_blue', 'Misc');
INSERT INTO `dvoo_items` VALUES (329, 'Construction Blueprint (rare)', 'bplan_r', 'Misc');
INSERT INTO `dvoo_items` VALUES (352, 'Powerful Soul', 'soul_red', 'Misc');
INSERT INTO `dvoo_items` VALUES (330, 'Construction Blueprint (very rare!)', 'bplan_e', 'Misc');
INSERT INTO `dvoo_items` VALUES (353, 'Weak Soul', 'soul_blue', 'Misc');
INSERT INTO `dvoo_items` VALUES (333, 'Construction Blueprint (very rare!)', 'bplan_e', 'Misc');
INSERT INTO `dvoo_items` VALUES (195, 'Stack of Papers', 'rp_sheets', 'Misc');
INSERT INTO `dvoo_items` VALUES (336, 'Construction Blueprint (very rare!)', 'bplan_e', 'Misc');
INSERT INTO `dvoo_items` VALUES (225, 'Shrewd citizen''s stash', 'chest_hero', 'Box');
INSERT INTO `dvoo_items` VALUES (297, 'Traveller''s corpse', 'cadaver', 'Food');
INSERT INTO `dvoo_items` VALUES (357, 'Stake Launcher', 'rlaunc', 'Weapon');
INSERT INTO `dvoo_items` VALUES (298, 'Gnawed corpse', 'cadaver_remains', 'Misc');
INSERT INTO `dvoo_items` VALUES (359, 'Hastily-built desk', 'bureau', 'Furniture');
INSERT INTO `dvoo_items` VALUES (358, 'Kalashni-Splash', 'kalach', 'Weapon');
INSERT INTO `dvoo_items` VALUES (360, 'Empty Vending Machine', 'distri', 'Furniture');
INSERT INTO `dvoo_items` VALUES (361, 'Santa''s reindeer', 'renne', 'Misc');
INSERT INTO `dvoo_items` VALUES (282, 'Second-hand Red Coat', 'christmas_suit_1', 'Misc');
INSERT INTO `dvoo_items` VALUES (284, 'Foul-smelling Red Hat', 'christmas_suit_3', 'Misc');
INSERT INTO `dvoo_items` VALUES (283, 'Ripped Red Trousers', 'christmas_suit_2', 'Misc');
INSERT INTO `dvoo_items` VALUES (285, 'Foul-smelling vintage suit', 'christmas_suit_full', 'Misc');