INSERT INTO `dvoo_titles` VALUES ('The Sneak', 'Professional Scout', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Shadow Master', 'Professional Scout', 25, 74);
INSERT INTO `dvoo_titles` VALUES ('Dune Ranger', 'Professional Scout', 75, 149);
INSERT INTO `dvoo_titles` VALUES ('Cleptomaniac', 'Thefts', 1032, 1254);
INSERT INTO `dvoo_titles` VALUES ('Seeker', 'Professional Scavenger', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Master Scavenger', 'Professional Scavenger', 25, 74);
INSERT INTO `dvoo_titles` VALUES ('Check out my knick-knacks', 'Professional Scavenger', 75, 149);
INSERT INTO `dvoo_titles` VALUES ('Dr Death''s Dietician', 'Cannibalism', 40, 79);
INSERT INTO `dvoo_titles` VALUES ('Defender', 'Professional Guardian', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Master Guardian', 'Professional Guardian', 25, 74);
INSERT INTO `dvoo_titles` VALUES ('Wandering Knight', 'Professional Guardian', 75, 149);
INSERT INTO `dvoo_titles` VALUES ('Last Bastion', 'Professional Guardian', 150, 299);
INSERT INTO `dvoo_titles` VALUES ('Noble Heart', 'Generosity', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Cantine Cook', 'Tasty Dishes', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Commis Chef', 'Tasty Dishes', 25, 49);
INSERT INTO `dvoo_titles` VALUES ('Demi Chef de Partie', 'Tasty Dishes', 40, 99);
INSERT INTO `dvoo_titles` VALUES ('Sous Chef', 'Tasty Dishes', 60, 485);
INSERT INTO `dvoo_titles` VALUES ('Master Chef', 'Tasty Dishes', 90, 992);
INSERT INTO `dvoo_titles` VALUES ('Pukka Chef', 'Tasty Dishes', 150, 1010);
INSERT INTO `dvoo_titles` VALUES ('Comic Book Fan', 'Heroic actions', 15, 29);
INSERT INTO `dvoo_titles` VALUES ('Extraordinary Citizen', 'Heroic actions', 30, 49);
INSERT INTO `dvoo_titles` VALUES ('Prodigy', 'Heroic actions', 50, 69);
INSERT INTO `dvoo_titles` VALUES ('Archaeologist', 'Excavations', 50, 299);
INSERT INTO `dvoo_titles` VALUES ('Just Say No !', 'Clean', 500, 998);
INSERT INTO `dvoo_titles` VALUES ('Bin Raker', 'Emancipation of the Shunned', 20, 99);
INSERT INTO `dvoo_titles` VALUES ('Tea Leaf', 'Thefts', 10, 29);
INSERT INTO `dvoo_titles` VALUES ('Artful Dodger', 'Thefts', 30, 39);
INSERT INTO `dvoo_titles` VALUES ('Chiseler', 'Thefts', 40, 49);
INSERT INTO `dvoo_titles` VALUES ('Ali Baba', 'Thefts', 50, 74);
INSERT INTO `dvoo_titles` VALUES ('Rusty Ryan', 'Thefts', 75, 99);
INSERT INTO `dvoo_titles` VALUES ('Danny Ocean', 'Thefts', 100, 499);
INSERT INTO `dvoo_titles` VALUES ('Casual S+M Enthusiast', 'Masochism', 20, 39);
INSERT INTO `dvoo_titles` VALUES ('Coquette', 'Decoration', 100, 249);
INSERT INTO `dvoo_titles` VALUES ('Pillager', 'Pillages', 30, 59);
INSERT INTO `dvoo_titles` VALUES ('Good Taste Personified', 'Decoration', 250, 499);
INSERT INTO `dvoo_titles` VALUES ('Plunderer', 'Pillages', 60, 99);
INSERT INTO `dvoo_titles` VALUES ('Viking', 'Pillages', 100, 469);
INSERT INTO `dvoo_titles` VALUES ('Silver Showerer', 'Sprinkler', 50, 99);
INSERT INTO `dvoo_titles` VALUES ('Corpse Cop', 'Removals', 60, 99);
INSERT INTO `dvoo_titles` VALUES ('Winners don''t take drugs!', 'Clean', 1000, 1483);
INSERT INTO `dvoo_titles` VALUES ('Community companion', 'Community Awards', 1, 4);
INSERT INTO `dvoo_titles` VALUES ('Local Butcher', 'Butcher', 30, 59);
INSERT INTO `dvoo_titles` VALUES ('Anyone for a fat-cat-kebab ?', 'Butcher', 60, 149);
INSERT INTO `dvoo_titles` VALUES ('Nuisance', 'Banishments', 10, 19);
INSERT INTO `dvoo_titles` VALUES ('Undesirable Type', 'Banishments', 20, 29);
INSERT INTO `dvoo_titles` VALUES ('Master Builder', 'Extreme Projects', 20, 49);
INSERT INTO `dvoo_titles` VALUES ('Nate Fortu', 'Luck', 5, 9);
INSERT INTO `dvoo_titles` VALUES ('Labourer', 'Constructions', 100, 199);
INSERT INTO `dvoo_titles` VALUES ('Builder', 'Constructions', 200, 399);
INSERT INTO `dvoo_titles` VALUES ('Site Manager', 'Constructions', 400, 699);
INSERT INTO `dvoo_titles` VALUES ('Architect', 'Constructions', 700, 1299);
INSERT INTO `dvoo_titles` VALUES ('Master Architect', 'Constructions', 1300, 1999);
INSERT INTO `dvoo_titles` VALUES ('Home depot regular', 'Repairs', 15, 29);
INSERT INTO `dvoo_titles` VALUES ('Fitter', 'Repairs', 30, 59);
INSERT INTO `dvoo_titles` VALUES ('Technician', 'Repairs', 60, 149);
INSERT INTO `dvoo_titles` VALUES ('Craftsman', 'Repairs', 150, 399);
INSERT INTO `dvoo_titles` VALUES ('Archeologist', 'Excavations', 50, 299);
INSERT INTO `dvoo_titles` VALUES ('Amateur Lab Rat', 'Lab Rat', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Exterminator', 'Zombies eliminated', 200, 299);
INSERT INTO `dvoo_titles` VALUES ('Mutilator', 'Zombies eliminated', 100, 199);
INSERT INTO `dvoo_titles` VALUES ('Corpse Crusher', 'Zombies eliminated', 300, 799);
INSERT INTO `dvoo_titles` VALUES ('The Hitman', 'Zombies eliminated', 800, 1999);
INSERT INTO `dvoo_titles` VALUES ('The Peacemaker', 'Zombies eliminated', 2000, 3999);
INSERT INTO `dvoo_titles` VALUES ('Fund re-allocation specialist', 'Golden Child', 1, 2);
INSERT INTO `dvoo_titles` VALUES ('Ultimate Fighter', 'Fights of despair', 20, 99);
INSERT INTO `dvoo_titles` VALUES ('Dora the Explorer', 'Distant Discoveries', 15, 29);
INSERT INTO `dvoo_titles` VALUES ('Fearless Adventurer', 'Distant Discoveries', 30, 69);
INSERT INTO `dvoo_titles` VALUES ('Guide to the World Beyond', 'Distant Discoveries', 70, 149);
INSERT INTO `dvoo_titles` VALUES ('Curious Reader', 'Roleplayer', 5, 9);
INSERT INTO `dvoo_titles` VALUES ('Storyteller', 'Roleplayer', 10, 19);
INSERT INTO `dvoo_titles` VALUES ('Suicide Sleeper', 'Daredevil Camper', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Alone in the Dark', 'Daredevil Camper', 25, 49);
INSERT INTO `dvoo_titles` VALUES ('Unshakeable Camper', 'Zen Camper', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Twinoid is taboo', 'Clean', 20, 74);
INSERT INTO `dvoo_titles` VALUES ('Happy as Larry', 'Clean', 75, 149);
INSERT INTO `dvoo_titles` VALUES ('Never touch the stuff, me.', 'Clean', 150, 499);
INSERT INTO `dvoo_titles` VALUES ('Just Say No!', 'Clean', 500, 999);
INSERT INTO `dvoo_titles` VALUES ('Guinea Pig', 'Drug Tests', 50, 99);
INSERT INTO `dvoo_titles` VALUES ('Meat Muncher', 'Cannibalism', 10, 39);
INSERT INTO `dvoo_titles` VALUES ('Dr. Death''s Dietician', 'Cannibalism', 40, 79);
INSERT INTO `dvoo_titles` VALUES ('Partially Decomposed', 'Deaths by Infection', 20, 39);
INSERT INTO `dvoo_titles` VALUES ('Whip me harder!', 'Masochism', 40, 59);
INSERT INTO `dvoo_titles` VALUES ('Moonlight Stroller', 'Nights in the desert', 20, 99);
INSERT INTO `dvoo_titles` VALUES ('Social Parasite', 'Banishments', 30, 105);
INSERT INTO `dvoo_titles` VALUES ('In with the bricks', 'In with the bricks', 1, 1);
INSERT INTO `dvoo_titles` VALUES ('Fund-reallocation Specialist', 'Golden Child', 1, 2);
INSERT INTO `dvoo_titles` VALUES ('Citizen Trafficker', 'Golden Child', 3, 4);
INSERT INTO `dvoo_titles` VALUES ('Fresh Flesh Peddler', 'Golden Child', 5, 9);
INSERT INTO `dvoo_titles` VALUES ('Community Spirit', 'Community Awards', 5, 9);
INSERT INTO `dvoo_titles` VALUES ('Trusted Neighbour', 'Ranked Towns', 2, 4);
INSERT INTO `dvoo_titles` VALUES ('Very Experienced Citizen', 'Ranked Towns', 5, 0);
INSERT INTO `dvoo_titles` VALUES ('Myth in the making', 'Legendary Towns!', 1, 1);
INSERT INTO `dvoo_titles` VALUES ('Mama''s Finest', 'Tasty Dishes', 100, 248);
INSERT INTO `dvoo_titles` VALUES ('Ultra Scavenger', 'Professional Scavenger', 150, 299);
INSERT INTO `dvoo_titles` VALUES ('Superhero in training', 'Heroic actions', 70, 89);
INSERT INTO `dvoo_titles` VALUES ('Always on the spot', 'Generosity', 25, 49);
INSERT INTO `dvoo_titles` VALUES ('Sand Phantom', 'Professional Scout', 151, 294);
INSERT INTO `dvoo_titles` VALUES ('Scourge of the animal kingdom...', 'Butcher', 150, 299);
INSERT INTO `dvoo_titles` VALUES ('I am legend.', 'Legendary Towns!', 2, 2);
INSERT INTO `dvoo_titles` VALUES ('Nonsense builder', 'Wonder Constructions', 1, 2);
INSERT INTO `dvoo_titles` VALUES ('Wild Beast Tamer', 'Professional Tamer', 75, 149);
INSERT INTO `dvoo_titles` VALUES ('Sand Baller', 'Sand Balls !', 10, 19);
INSERT INTO `dvoo_titles` VALUES ('Talks To The Animals', 'Professional Tamer', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Legend of Labrador', 'Professional Tamer', 25, 74);
INSERT INTO `dvoo_titles` VALUES ('Town Planner', 'Constructions', 2002, 2997);
INSERT INTO `dvoo_titles` VALUES ('Soul salesman', 'Golden Child', 10, 11);
INSERT INTO `dvoo_titles` VALUES ('Master Thief', 'Thefts', 500, 949);
INSERT INTO `dvoo_titles` VALUES ('Social Animal', 'Community Awards', 10, 14);
INSERT INTO `dvoo_titles` VALUES ('Extreme Explorer', 'Expert Expeditions', 5, 14);
INSERT INTO `dvoo_titles` VALUES ('Potion Preparer', 'Lab Rat', 25, 49);
INSERT INTO `dvoo_titles` VALUES ('Brave Prospector', 'Distant Discoveries', 150, 199);
INSERT INTO `dvoo_titles` VALUES ('Inspiration for the people', 'Ranked Towns', 5, 9);
INSERT INTO `dvoo_titles` VALUES ('Body Bouncer', 'Removals', 100, 199);
INSERT INTO `dvoo_titles` VALUES ('Golden Showerer', 'Sprinkler', 100, 196);
INSERT INTO `dvoo_titles` VALUES ('Somewhere there''s a battery with your name on it...', 'Battery Launcher Builder', 15, 24);
INSERT INTO `dvoo_titles` VALUES ('Carrier of the Sickness', 'Deaths by Infection', 52, 74);
INSERT INTO `dvoo_titles` VALUES ('Sand Shifter', 'Excavations', 300, 694);
INSERT INTO `dvoo_titles` VALUES ('Champion of the people', 'Heroic actions', 90, 119);
INSERT INTO `dvoo_titles` VALUES ('Chuck Norris', 'Zombies eliminated', 4008, 5896);
INSERT INTO `dvoo_titles` VALUES ('Lab Rat', 'Drug Tests', 100, 149);
INSERT INTO `dvoo_titles` VALUES ('Charitable Soul', 'Generosity', 25, 49);
INSERT INTO `dvoo_titles` VALUES ('Attach the testicle clamps!', 'Masochism', 60, 99);
INSERT INTO `dvoo_titles` VALUES ('Danse avec les zombies', 'Daredevil Camper', 50, 74);
INSERT INTO `dvoo_titles` VALUES ('Animated Corpse', 'Community Awards', 15, 15);
INSERT INTO `dvoo_titles` VALUES ('Check out my skin sombrero!', 'Cannibalism', 80, 119);
INSERT INTO `dvoo_titles` VALUES ('Wild-eyed Wanderer', 'Nights in the desert', 100, 182);
INSERT INTO `dvoo_titles` VALUES ('Christopher Wren', 'Constructions', 3002, 4978);
INSERT INTO `dvoo_titles` VALUES ('Not without my dog!', 'Professional Tamer', 150, 292);
INSERT INTO `dvoo_titles` VALUES ('Corner Chemist', 'Lab Rat', 50, 95);
INSERT INTO `dvoo_titles` VALUES ('Interior designer', 'Decoration', 500, 988);
INSERT INTO `dvoo_titles` VALUES ('Tenzing Norgay', 'Distant Discoveries', 200, 609);
INSERT INTO `dvoo_titles` VALUES ('Dumpster Diver', 'Emancipation of the Shunned', 101, 136);
INSERT INTO `dvoo_titles` VALUES ('Founder of Timewasting', 'Wonder Constructions', 3, 6);
INSERT INTO `dvoo_titles` VALUES ('Social Support', 'Generosity', 50, 53);
INSERT INTO `dvoo_titles` VALUES ('I''m Batman', 'Heroic actions', 120, 149);
INSERT INTO `dvoo_titles` VALUES ('Desert Historian', 'Roleplayer', 20, 29);
INSERT INTO `dvoo_titles` VALUES ('Expeditions Expert', 'Expert Expedtions', 15, 29);
INSERT INTO `dvoo_titles` VALUES ('Great Architect', 'Extreme Projects', 50, 99);
INSERT INTO `dvoo_titles` VALUES ('Super Soaker', 'Water Guns', 10, 14);
INSERT INTO `dvoo_titles` VALUES ('Follow me if you want to live!', 'Legendary Towns!', 3, 6);
INSERT INTO `dvoo_titles` VALUES ('Post-mortem Pickpocket', 'Pillages', 200, 399);
INSERT INTO `dvoo_titles` VALUES ('Hugry Jackal', 'Pillages', 405, 587);
INSERT INTO `dvoo_titles` VALUES ('If we''re meant to eat vegetables, why are  animals so tasty ?', 'Butcher', 300, 389);
INSERT INTO `dvoo_titles` VALUES ('Key hee hee!', 'Covert Concierge', 1, 4);
INSERT INTO `dvoo_titles` VALUES ('Wormfinder General', 'Professional Survivalist', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Blood ''n'' Bile Spitter', 'Deaths by Infection', 75, 98);
INSERT INTO `dvoo_titles` VALUES ('If I had known, I wouldn''t have come', 'Ruin Exploration', 5, 9);
INSERT INTO `dvoo_titles` VALUES ('Sneaky Voyager', 'Ruin Explorations', 5, 19);
INSERT INTO `dvoo_titles` VALUES ('I''ll let myself in', 'Professional Technician', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('I don''t miss anything.', 'Professional Scavenger', 300, 474);
INSERT INTO `dvoo_titles` VALUES ('How about some Chubb-ly?', 'Covert Concierge', 5, 9);
INSERT INTO `dvoo_titles` VALUES ('Community Ãœber-Activist', 'Community Awards', 20, 25);
INSERT INTO `dvoo_titles` VALUES ('MacGyver of the World beyond', 'Repairs', 401, 544);
INSERT INTO `dvoo_titles` VALUES ('Platinum Showerer', 'Sprinkler', 211, 364);
INSERT INTO `dvoo_titles` VALUES ('The BRD Screwdriver Combo', 'Professional Technician', 25, 74);
INSERT INTO `dvoo_titles` VALUES ('Master Rootfinder', 'Professional Survivalist', 25, 74);
INSERT INTO `dvoo_titles` VALUES ('Town plasterer', 'Building Repairs', 100, 248);
INSERT INTO `dvoo_titles` VALUES ('Zen-ergizer', 'Battery Launcher Builder', 25, 32);
INSERT INTO `dvoo_titles` VALUES ('Sesame, shift your A...', 'Covert Concierge', 10, 14);
INSERT INTO `dvoo_titles` VALUES ('I see dead people - everywhere !', 'Daredevil Camper', 75, 95);
INSERT INTO `dvoo_titles` VALUES ('Saver of Mankind', 'Heroic actions', 150, 176);
INSERT INTO `dvoo_titles` VALUES ('Stiff Shifter', 'Removals', 201, 292);
INSERT INTO `dvoo_titles` VALUES ('Product Tester', 'Lab Rat', 107, 202);
INSERT INTO `dvoo_titles` VALUES ('All-round Handyman', 'Building Repairs', 250, 499);
INSERT INTO `dvoo_titles` VALUES ('Zombies'' favourite', 'Last Man Standing', 10, 13);
INSERT INTO `dvoo_titles` VALUES ('Fleet-footed Coyote', 'Pillages', 600, 962);
INSERT INTO `dvoo_titles` VALUES ('Wild Beast', 'Fights of despair', 106, 106);
INSERT INTO `dvoo_titles` VALUES ('Taught Sam Fisher everything he knows!', 'Professional Scout', 300, 545);
INSERT INTO `dvoo_titles` VALUES ('Saviour of Citizenkind', 'Heroic actions', 150, 199);
INSERT INTO `dvoo_titles` VALUES ('Confirmed sleepwalker', 'Ruin Exploration', 10, 30);
INSERT INTO `dvoo_titles` VALUES ('Jean Claude Van Damned', 'Zombies eliminated', 6250, 9792);
INSERT INTO `dvoo_titles` VALUES ('Gentleman Robber', 'Covert Concierge', 20, 28);
INSERT INTO `dvoo_titles` VALUES ('Sandman', 'Sand balls!', 10, 12);
INSERT INTO `dvoo_titles` VALUES ('Insatiable Citizen', 'Professional Survivalist', 75, 149);
INSERT INTO `dvoo_titles` VALUES ('deadbolt Dick', 'Covert Concierge', 15, 19);
INSERT INTO `dvoo_titles` VALUES ('Spanners and Bump keys', 'Professional Technician', 75, 147);
INSERT INTO `dvoo_titles` VALUES ('Harbinger of the Plague', 'Deaths by Infection', 100, 144);
INSERT INTO `dvoo_titles` VALUES ('Regularly A-mazed!', 'Ruin Explorations', 20, 49);
INSERT INTO `dvoo_titles` VALUES ('Hell is a walk in the park.', 'Last Man Standing - Hardcore!', 5, 9);
INSERT INTO `dvoo_titles` VALUES ('Horizon traveller', 'Expert Expeditions', 30, 67);
INSERT INTO `dvoo_titles` VALUES ('Legend of the World Beyond', 'Heroic actions', 200, 318);
INSERT INTO `dvoo_titles` VALUES ('One town to rule them all!', 'Clash Titan', 1, 1);
INSERT INTO `dvoo_titles` VALUES ('Bring out the gimp!', 'Masochism', 100, 146);
INSERT INTO `dvoo_titles` VALUES ('Lunches like Lecter', 'Cannibalism', 120, 178);
INSERT INTO `dvoo_titles` VALUES ('I am a god! I will live forever!', 'Clash Champion', 1, 2);
INSERT INTO `dvoo_titles` VALUES ('Great Mason', 'Extreme Projects', 100, 149);
INSERT INTO `dvoo_titles` VALUES ('You... shall... not...PASS !', 'Professional Guardian', 300, 304);
INSERT INTO `dvoo_titles` VALUES ('Tunnel Visionary', 'Ruin Explorations', 10, 19);
INSERT INTO `dvoo_titles` VALUES ('Hungry Jackal', 'Pillages', 400, 597);
INSERT INTO `dvoo_titles` VALUES ('Why the X would I want a caravan that''s got no X wheels', 'The leprechaun got you good', 110, 624);
INSERT INTO `dvoo_titles` VALUES ('Irish eyes are smiling - because they''ve nicked your stuff!', 'The leprechaun got you good', 15, 19);
INSERT INTO `dvoo_titles` VALUES ('This leprechaun is unstoppable.â€', 'The leprechaun got you good', 55, 68);
INSERT INTO `dvoo_titles` VALUES ('Burn him, see if his ashes turn green!', 'The leprechaun got you good', 75, 99);
INSERT INTO `dvoo_titles` VALUES ('Masterpieces in Peril', 'Building Repairs', 504, 833);
INSERT INTO `dvoo_titles` VALUES ('I thought they granted wishes, the thieving pikey!', 'The leprechaun got you good', 32, 42);
INSERT INTO `dvoo_titles` VALUES ('Irish pockets are bulging!', 'The leprechaun got you good', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Tin-soul town', 'Soul Value', 500, 999);
INSERT INTO `dvoo_titles` VALUES ('O soul-e mio', 'Soul Value', 100, 499);
INSERT INTO `dvoo_titles` VALUES ('A caravan with no wheels???', 'The leprechaun got you good', 100, 625);
INSERT INTO `dvoo_titles` VALUES ('Soul-dier', 'Soul Value', 2000, 2999);
INSERT INTO `dvoo_titles` VALUES ('Noble Soul', 'Soul Value', 1000, 1999);
INSERT INTO `dvoo_titles` VALUES ('Armageddon Witness', 'Armageddon Witness', 1, 1);
INSERT INTO `dvoo_titles` VALUES ('Where''s my pot of gold, thieving pikey!', 'The leprechaun got you good', 25, 49);
INSERT INTO `dvoo_titles` VALUES ('Shim Surgeon', 'Covert Concierge', 30, 32);
INSERT INTO `dvoo_titles` VALUES ('Desert Orphan', 'Zen Camper', 27, 29);
INSERT INTO `dvoo_titles` VALUES ('Don''t wait up...', 'Daredevil Camper', 100, 149);
INSERT INTO `dvoo_titles` VALUES ('Keen Sceptic', 'Mystic Points', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Type 4 Encouter', 'Soul Collector', 2, 9);
INSERT INTO `dvoo_titles` VALUES ('I''ll let myself in...', 'Professional Technician', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Certified Charlatan', 'Professional Shaman', 10, 24);
INSERT INTO `dvoo_titles` VALUES ('Legend of Labradoodle', 'Professional Tamer', 25, 74);
INSERT INTO `dvoo_titles` VALUES ('Dances with zombies', 'Daredevil Camper', 50, 74);
INSERT INTO `dvoo_titles` VALUES ('Expedition Expert', 'Expert Expeditions', 15, 29);
INSERT INTO `dvoo_titles` VALUES ('Anyone for a fat-cat-kebab?', 'Butcher', 60, 149);
INSERT INTO `dvoo_titles` VALUES ('Reincarnator', 'Soul Value', 3002, 4994);
INSERT INTO `dvoo_titles` VALUES ('I see dead people - everywhere!', 'Daredevil Camper', 75, 99);
INSERT INTO `dvoo_titles` VALUES ('The name''s Nate Fortu', 'Luck', 5, 9);
INSERT INTO `dvoo_titles` VALUES ('Psychic for rent', 'Soul Collector', 20, 29);
INSERT INTO `dvoo_titles` VALUES ('Have you got a light?', 'Soul Collector', 10, 19);
INSERT INTO `dvoo_titles` VALUES ('Daylight Lantern', 'Spiritual Guide', 301, 990);
INSERT INTO `dvoo_titles` VALUES ('There''s a battery with your name on it...', 'Battery Launcher Builder', 15, 24);
INSERT INTO `dvoo_titles` VALUES ('This leprechaun is unstoppable.', 'The leprechaun got you good', 50, 74);
INSERT INTO `dvoo_titles` VALUES ('Rat Roaster', 'Professional Survivalist', 150, 288);
INSERT INTO `dvoo_titles` VALUES ('Desert Orphant', 'Zen Camper', 26, 43);
INSERT INTO `dvoo_titles` VALUES ('Divine Soul', 'Soul Value', 5003, 6661);
INSERT INTO `dvoo_titles` VALUES ('Accursed Soothsayer', 'Professional Shaman', 25, 73);
INSERT INTO `dvoo_titles` VALUES ('Zombie favourite', 'Last Man Standing', 10, 14);
INSERT INTO `dvoo_titles` VALUES ('Winners don''t use drugs!', 'Clean', 1000, 2042);
INSERT INTO `dvoo_titles` VALUES ('You... shall... not...PASS!', 'Professional Guardian', 307, 478);
INSERT INTO `dvoo_titles` VALUES ('Capitaine Crochet', 'Covert Concierge', 32, 36);
INSERT INTO `dvoo_titles` VALUES ('LÃ©gende de l''Outre-Monde', 'Heroic actions', 200, 251);
INSERT INTO `dvoo_titles` VALUES ('Highly experienced player', 'Ranked Towns', 10, 14);
INSERT INTO `dvoo_titles` VALUES ('Tireless tumbler tickler', 'Professional Technician', 152, 288);
INSERT INTO `dvoo_titles` VALUES ('Last Boy Scout', 'Last Man Standing', 15, 17);
INSERT INTO `dvoo_titles` VALUES ('Dog food doesn''t taste so bad', 'Professional Tamer', 305, 494);
INSERT INTO `dvoo_titles` VALUES ('Enlightened Builder', 'Wonder Constructions', 7, 8);
INSERT INTO `dvoo_titles` VALUES ('If we''re meant to eat vegetables, why are animals so tasty?', 'Butcher', 303, 440);
INSERT INTO `dvoo_titles` VALUES ('Compass Included', 'Ruin Explorations', 53, 63);
INSERT INTO `dvoo_titles` VALUES ('Type 4 Encounter', 'Soul Collector', 2, 9);
INSERT INTO `dvoo_titles` VALUES ('Do you feel lucky, punk?', 'Luck', 10, 12);
INSERT INTO `dvoo_titles` VALUES ('Librarian', 'Roleplayer', 30, 38);
INSERT INTO `dvoo_titles` VALUES ('Terraforming Specialist', 'Extreme Projects', 150, 196);
INSERT INTO `dvoo_titles` VALUES ('Marquee Master', 'Decoration', 1001, 1293);
INSERT INTO `dvoo_titles` VALUES ('Desert Shackleton', 'Expert Expeditions', 70, 98);
INSERT INTO `dvoo_titles` VALUES ('It''s just too easy.', 'Last Man Standing - Hardcore!', 10, 14);
INSERT INTO `dvoo_titles` VALUES ('Soul Calipers', 'Mystic Points', 25, 55);
INSERT INTO `dvoo_titles` VALUES ('Amophilis psychotropia', 'Soul Collector', 30, 48);
INSERT INTO `dvoo_titles` VALUES ('Solicitor of the World Beyond', 'Pillages', 1009, 1391);
INSERT INTO `dvoo_titles` VALUES ('Pocket Companion', 'Spiritual Guide', 1074, 1295);
INSERT INTO `dvoo_titles` VALUES ('Product Tester!', 'Drug Tests', 150, 194);
INSERT INTO `dvoo_titles` VALUES ('Blue Fire-breather', 'Soul Collector', 50, 79);
INSERT INTO `dvoo_titles` VALUES ('In at the deep end!', 'Clash Team', 1, 2);
INSERT INTO `dvoo_titles` VALUES ('Making things happen!', 'Clash CEO', 1, 1);
INSERT INTO `dvoo_titles` VALUES ('Partially Putrified', 'Deaths by Infection', 20, 33);
INSERT INTO `dvoo_titles` VALUES ('Soul Recycler', 'Professional Shaman', 76, 147);
INSERT INTO `dvoo_titles` VALUES ('I see dead people 0_0', 'Soul Collector', 85, 104);
INSERT INTO `dvoo_titles` VALUES ('Man vs World Beyond', 'Daredevil Camper', 151, 218);
INSERT INTO `dvoo_titles` VALUES ('Wannabe Zombie...', 'Cannibalism', 182, 190);
INSERT INTO `dvoo_titles` VALUES ('Plim-Soul', 'Soul Collector', 121, 146);
INSERT INTO `dvoo_titles` VALUES ('I''ve got a sore tummy...', 'Deaths by Infection', 150, 150);
INSERT INTO `dvoo_titles` VALUES ('Pillar of the community', 'Ranked Towns', 15, 16);
INSERT INTO `dvoo_titles` VALUES ('Who you gonna call?', 'Soul Collector', 162, 179);
INSERT INTO `dvoo_titles` VALUES ('Go ahead, make my day!', 'Zombies eliminated', 10044, 10719);
INSERT INTO `dvoo_titles` VALUES ('Watches with Scouts', 'Mystic Points', 76, 86);
INSERT INTO `dvoo_titles` VALUES ('TechnicoMecanoMegalo', 'Professional Technician', 309, 309);
INSERT INTO `dvoo_titles` VALUES ('One Eye Open', 'Watchman', 20, 35);
INSERT INTO `dvoo_titles` VALUES ('What do you mean these ain''t skittles', 'Drug Tests', 201, 241);
INSERT INTO `dvoo_titles` VALUES ('Friends? Who needs ''em!', 'Professional Survivalist', 304, 317);
INSERT INTO `dvoo_titles` VALUES ('Ruin Restorer', 'Excavations', 858, 894);
INSERT INTO `dvoo_titles` VALUES ('Apocalyptic Garbageman', 'Removals', 301, 354);
INSERT INTO `dvoo_titles` VALUES ('Don''t cross the streams', 'Soul Collector', 182, 183);
INSERT INTO `dvoo_titles` VALUES ('Get some Duct Tape in there.', 'Building Repairs', 1025, 1025);
INSERT INTO `dvoo_titles` VALUES ('Both Eyes Open', 'Watchman', 40, 56);
INSERT INTO `dvoo_titles` VALUES ('Great, benevolent, all-powerful creator', 'Extreme Projects', 201, 201);
INSERT INTO `dvoo_titles` VALUES ('Open-chakra', 'Soul Value', 7091, 7091);
INSERT INTO `dvoo_titles` VALUES ('Soul Mason', 'Wonder Constructions', 10, 10);
